import type { Metadata } from 'next'
import { NotoSansKr } from '@/style/fonts'
import './globals.css'
import Gnb from '@/app/ui/navigation/Gnb'
import { cn } from '@/lib/utils'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={cn(NotoSansKr.className)}>
        <Gnb />
        {children}
      </body>
    </html>
  )
}
